#!/bin/bash

s3_object_exists() {
  # requires: s3:HeadObject
  if [[ -z "$1" ]]; then
    echo "usage: s3_object_exists \$bucket_name \$key"
    return 1
  elif [[ "$1" =~ -h|--help ]]; then
    echo "usage: s3_object_exists \$bucket_name \$key"
    return 0
  fi

  stdall="$(aws s3api head-object --bucket="$1" --key="$2" 2>&1)"
  exit_code=$?
  
  echo -e "[DEBUG] STDALL\n$stdall"

  if [[ "$stdall" == *404* ]]; then
    return 1
  elif [[ $exit_code -eq 0 ]]; then
    return 0
  else
    printf "$stdall\n" 1>&2
    return 1
  fi
}