#!/bin/bash

s3_url() {
  if [[ -z "$1" ]]; then
    echo "usage: s3_url \$bucket_name [\$key]"
    return 1
  elif [[ "$1" =~ -h|--help ]]; then
    echo "usage: s3_url \$bucket_name [\$key]"
    return 0
  fi
  
  echo "[DEBUG] got thru entry ifs"

  if [[ -n "$2" ]] && [[ "$2" == /* ]]; then
    key="$2"
  elif [[ -z "${2// }" ]]; then
    key=""
  else
    key="/$2"
  fi

  echo "https://$1.s3.amazonaws.com$key"
}