name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    name: test aws-actions-cheats on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest]
    steps:
      - uses: chiefbiiko/aws-actions-cheats@master
      - run: |
          ls /usr/local/bin | grep s3
          echo "$PATH"
      - run: |
          s3_url test-bucket test-key
          s3_uri test-bucket test-key