name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    name: test aws-actions-cheats on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: chiefbiiko/aws-actions-cheats@${{ env.GITHUB_SHA }}
      - run: printf "$(s3_url test-bucket test-key)\n"