name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test aws-actions-cheats on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: .
      - run: printf "$(s3_url test-bucket test-key)\n"